### ISSUE TITLE
Why is "Balance Distribution" showing shares instead of balances?

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#1545]
https://explorer.dev.oasis.io/testnet/consensus/validators/oasis1qpz97gfrvj5xzx8jx7x9zweeq0rcf2q6jg4a09qz
![explorer dev oasis io_testnet_consensus_validators_oasis1qpz97gfrvj5xzx8jx7x9zweeq0rcf2q6jg4a09qz](https://github.com/user-attachments/assets/b33db292-dc8f-401b-8287-849f77d7e8f6)

https://testnet.nexus.prd.oasis.io/v1/consensus/validators/oasis1qpz97gfrvj5xzx8jx7x9zweeq0rcf2q6jg4a09qz
```json
        "active_balance": "11519491447527",
        "active_balance_24": "11643393355099",
        "active_shares": "10186532790671",
        "debonding_balance": "224688870953",
        "debonding_shares": "224688870953",
        "num_delegators": 4,
        "self_delegation_balance": "11308549910208",
        "self_delegation_shares": "10000000000000"
```

**Comment by buberdds** [comment]
https://www.figma.com/design/8dwSyYOOm3vlgbvxPGT29p?node-id=8694-95348#786967216

**Comment by lukaw3d** [comment]
@donouwens

**Comment by Andrew7234** [comment]
For calculating self delegations (or any user's staked balance with a validator) we end up [rounding the balance](https://github.com/oasisprotocol/nexus/blob/main/storage/client/queries/queries.go#L370) to the nearest base unit. In practice this is a very small error since 1 rose = 10^9 base units, so it shouldn't make much of a difference to use shares/balance for percentage calculations. 

I initially liked the idea of using shares since Nexus tracks those explicitly, and they don't change as often due to epoch staking rewards. But I agree that the 'rose balance' should take precedence over the 'shares'. I like Don's suggestion of showing the balance by default and displaying shares in the tooltip/hover, does that sound ok?
