### ISSUE TITLE
[Bug]: Cant navigate to emerald dashboard from homepage on mobile

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### STEPS TO REPRODUCE

1. Open homepage on mobile
2. Click emerald
3. See emerald tooltip
4. Click emerald
5. Tooltip disappears
6. Click emerald
7. Tooltip appears
8. ...

**Comment by buberdds** [comment]
@lukaw3d I think this part works as expected. When you click Emerald, you have to click tooltip content. Otherwise you click tooltip overlay which closes a tooltip. 

Other things that are not correct
- icons are incorrect. Clock icon should be used for disabled layers, for active layers we should use icon that we use in subpage header and layer modal 
- we need to update labels
- Cipher and consensus should be both in disabled state

**Comment by lubej** [comment]
Right, the original issue works as expected.
https://www.loom.com/share/972bb866aa244dcf9cf2383361c61b1b?focus_title=1&muted=1&from_recorder=1

As @buberdds mentioned the items in list are not correct, will update.
