### ISSUE TITLE
[Bug]: "Consensus layer indexer is not caught up" sounds wrong

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#557]
https://github.com/oasisprotocol/explorer/blob/a77aa3ac81aa59ba4dd532f2fb4db90161052ce9/src/locales/en/translation.json#L95

**Comment by lukaw3d** [comment]
wait, is the source of that information actually the consensus?

**Comment by csillag** [comment]
We display this when we get `active_nodes: 0` for a runtime status. However, the indexer guys have explained to us that this typically happens when the consensus  parsing is behind. So consensus is not the direct source of this information, but it's the most likely underlying cause of the situation that triggers this.
